openapi: 3.0.1
info:
  title: monster-lantern-archon
  x-cortex-tag: monster-lantern-archon
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: celestial
    challenge_rating: 2
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-lantern-archon
      alias: github-token-test
